permalink:   none
lsi:         false
highlighter: pygments
destination: public
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
exclude:
  - script
  - Guardfile
  - README.markdown

title: "Why의 (감동적인) 루비 가이드"
